### ISSUE TITLE
Be able to select text with keyboard

### ISSUE THREAD

**Issue by MatthK** [immense/Remotely#396]
When working on a remote machine in the browser window and trying to select text in a program with the keyboard (pressing shift + arrow keys), the text does not get selected. It's only possible to select text via selecting it via the mouse.

I can't select text in all kinds of programs used on the remote machine (web forms, text editor, etc.)

It would be helpful if selecting text would work with the keyboard only as well. I.e. to select a whole row of text, pressing shift + down arrow.

Text can be selected with the mouse, so there is a perfectly working work-around. It's just a comfort function.

Desktop: Microsoft Edge Version 95.0.1020.53 (Official build) (64-bit)
Remotely: Version: 2021.08.17.1435

**Comment by stevesobol** [comment]
I have a solution. I just haven't had time to implement it yet.

If you don't want your web browser to steal keystrokes, the best solution is to not use a web browser in the first place.

The problem you're having doesn't exist with other remote control solutions like ConnectWise Control, TeamViewer, etc., because those products have viewers that are desktop apps. Certain key combinations like Windows-L, Windows-R and Ctrl-Alt-Delete are captured by Windows (Ctrl-Alt-Delete is also captured by Linux) and those key combinations, you won't be able to directly use, but most others, you can.

This is an enhancement I definitely want to implement, but I haven't had the time. This one and Mac support are the two big enhancements I want to take point on once I have the bandwidth to do so.

**Comment by MatthK** [comment]
That's fair enough. I do believe the product is really really cool and I love it. I do understand that in a browser window capturing keyboard shortcuts is tricky.

I am fine with the workarounds (using the mouse).

**Comment by MatthK** [comment]
As a feature request, when you work on the above new solution, I suggest to also be able to send the keyboard shortcut WINDOWS-KEY + L to lock a windows session before disconnecting from the remote machine.

**Comment by bitbound** [comment]
This issue has been grouped under pinned issue #688 .  Please comment there if you're still having issues in the latest release.
