### ISSUE TITLE
Issues with NGINX Proxy Manager

### ISSUE THREAD

**Issue by iTABHayden** [immense/Remotely#550]
Clients are constantly disconnecting and reconnecting to docker behind NGINX Proxy Manager. This is happening in version 2023.01.02.1403 and older legacy (non docker) version 2022.09.16.1006. This is with the correct NGINX config on the legacy version and on the NGINX Proxy Manager side as guided in the NGINX setup here https://hub.docker.com/r/immybot/remotely.

Docker Server
Remotely Version: 2023.01.02.1403
OS: Debian 11
Docker Version: 20.10.22, build 3a2c30b
Tried with docker compose and docker command line with the same result.

Legacy Server
Remotely Version: 2022.09.16.1006
OS: Ubuntu 20.04.5 LTS

I am wondering if this is a bug or some configuration I am missing? Appreciate some discussion.

**Comment by stevesobol** [comment]
I had a similar problem with Remotely behind haproxy, and it turned out that I had to watch for the HTTP Upgrade: header and handle upgraded (websocket) connections differently than regular HTTP connections. I believe they required a longer timeout.

Unfortunately, I do not have the configs anymore. It appears that I may have deleted them, and I haven't played with haproxy in a while, otherwise I'd share a gist containing the relevant snippets from my config, in the hopes that maybe that would help you figure out how to configure nginx. I don't see a post about haproxy or websockets on the r/Remotely_App [subreddit](https://www.reddit.com/r/remotely_app/), either.

**Comment by iTABHayden** [comment]
Wow, thanks so much for that info @stevesobol. I really, really appreciate it as this has solved my problem. I literally just enabled Websocket Support and HTTP/2 and boom. Working just fine. 2 simple sliders saved a whole day troubleshooting! Sometimes one does fell stupid. Thanks again mate.
