### ISSUE TITLE
Windows protected your PC Msg on Windows 11

### ISSUE THREAD

**Issue by jakes670** [immense/Remotely#551]
**Is your feature request related to a problem? Please describe.**
Windows gives a error when you open the Portable Instant Support Clients

Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk
App: | Remotely_Desktop.exe
Publisher: | Unknown

**Describe the solution you'd like**
Exe must lunch without this warning

**Describe alternatives you've considered**
User will need to click on "more info:" then they must click on "Run Anyway"

**Additional context**

![image](https://user-images.githubusercontent.com/31097840/210359121-4c357235-9e8f-49a2-af69-91867be8a641.png)

**Comment by lucent-sea** [comment]
Getting this message to go away would require, at minimum, a code signing certificate.  These can cost up to $300.

There's no guarantee that SmartScreen warnings will go away once the EXE is signed.  The certificate (i.e. "the publisher") has to gain enough reputation in their system in order for it to be trusted.  As far as I know, Microsoft doesn't publish information about how their reputation system works.

You can [submit the file for review](https://learn.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview#submit-files-to-microsoft-defender-smartscreen-for-review), but without a digital certificate from a trusted root certificate authority, it probably won't do anything.

I never wanted to spend money on it since it wasn't even guaranteed to do anything.  I don't know if Immense Networks (the new owner of Remotely) has plans to sign the binaries with a commercial certificate.

In the meantime, if you have your own certificate or want to purchase one, you can sign the files with it and see if it helps.
