### ISSUE TITLE
Client scheme (http/https) and X-Forwarded-Proto

### ISSUE THREAD

**Issue by Natan738** [immense/Remotely#573]
Gostaria de saber como fazer para que ao baixar o o agente nas maquinas a url já venha com https.
ex.: https://remotely.domain.com
Hoje está puxando http://remotely.domain.com e por conta disso não está conectando ao server.

**Comment by DeAlexPesh** [comment]
make an option with this fackin protocol. please.
https://github.com/immense/Remotely/issues/564
https://github.com/immense/Remotely/issues/547

**Comment by lucent-sea** [comment]
@DeAlexPesh I'd like to point out that many of the contributors here (myself included) are donating their time to work on this project.  They aren't being paid for it.  So please keep that in mind when communicating.

That said, I have yet to see any evidence that it's not working correctly.  I have multiple Remotely servers running behind proxies, and they all work.

First, make sure you're using the latest Remotely image version.  Then if you enable "Use HTTP Logging" in the Server Config page, restart the container, and download the instant support client or Windows installer, you'll see logs like the below screenshot.

As you can see, the request came in over `http`.  It had the header `X-Forwarded-Proto: https`.  And because that header was there, the effective scheme for the request was changed to https.  You can try it yourself at https://remotely-la.jaredg.dev.

If you can show me a screenshot of this not working, where the header is set correctly but the effective scheme isn't updated, then I'll code a workaround.  Until I have proof, I'm pretty confident that your `$proxy_x_forwarded_proto` variable is `http`.

Just change your Nginx config to `proxy_set_header X-Forwarded-Proto https;` to force the request to be seen as HTTPS.

![image](https://user-images.githubusercontent.com/20995508/214308793-10b5a25c-2aeb-46e8-b0f7-9e34afbb1425.png)

**Comment by lucent-sea** [comment]
> You are not paid for what you do. Ok.

I built Remotely over the course of several years during my spare time, while also working a full-time job that was completely unrelated to the project.  It's always been free and open-source.  Nobody's making money off of Remotely.

> Do you not have confirmation that the headers don't work?
> 10% of questions about the client and his protocol, but you pretend everything is fine?

This is the first time I've gotten logs.  I haven't been able to reproduce it in my environment.  I didn't write the code that parses the headers.  It's all Microsoft's code.

There are nearly 2 million pulls of the Docker image, and tens of thousands of downloads from GitHub releases.  The vast majority are working fine.

So when a handful of reports come in about an issue, one that I can't reproduce and is primarily related to Microsoft's code, I need to verify with certainty before making changes.  And if there's a real issue, I want to fix the source of it, as opposed to creating a workaround.

You said you're behind a firewall and reverse proxy, right?  I see that `X-Forwarded-For` only contains `192.168.1.141`.  With your configuration, I'd expect to see multiple values here, in [this format](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#syntax).  A single IP there would be if it's only forwarded once (e.g. reverse proxy is directly facing the internet), and the IP would be the remote client.

```
X-Forwarded-For: <client>, <proxy1>, <proxy2>
```

Each proxy in the `X-Forwarded-For` list would need to be added to `KnownProxies` in appsettings.json.  If the proxy closest to the ASP.NET Core app is not localhost, then that also needs to be added.  Finally, if the Docker host isn't the default 172.17.0.1, that will need to be added too.   Otherwise, ASP.NET Core won't accept the forwarded headers (for security reasons)

For reference, the full docs can be found [here](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0).  [This](https://github.com/immense/Remotely/blob/master/Server/Program.cs#L140) is where I'm enabling forwarded headers and setting the options.  The rest is handled by ASP.NET Core's internal middleware.

**Comment by lucent-sea** [comment]
If you can try making those updates and send the logs again, that would be appreciated.  Please also include the line below what you showed, where it outputs the parsed/effective values.

**Comment by DeAlexPesh** [comment]
>  I want to fix the source of it, as opposed to creating a workaround.
Is good (not a bug but a feature).
But there is a practice of specifying the connection string directly in the settings. It's normal, as alternative.
Docker can change IP after container re-creation. And everything will break?
And just a request:
Make please a choice of customization colors with hex input...
and the ability to add append custom css.
Thank you

**Comment by Natan738** [comment]
Boa Tarde,
@lucent-sea alguma novidade de como posso resolver esse problema?
gostaria de fazer a implantação nas maquinas do dominio usando o GPO, porém o instalador do agente está puxando o http ou invés de https e com isso os agente não conecta nas maquinas.
segue o erro que acontece nos agente das estações.

info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
      Start processing HTTP request HEAD http://remotely.intuiciondeluxe.com.br/Content/Remotely-Win10-x64.zip
info: System.Net.Http.HttpClient.Default.ClientHandler[100]
      Sending HTTP request HEAD http://remotely.intuiciondeluxe.com.br/Content/Remotely-Win10-x64.zip
info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response headers after 269.0597ms - 304
info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 334.4786ms - 304
info: Remotely.Agent.Services.UpdaterWin[0]
      Service Updater: Version is current.
info: Remotely.Agent.Services.AgentHubConnection[0]
      Attempting to connect to server.
fail: Remotely.Agent.Services.AgentHubConnection[0]
      Error while connecting to server.
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 405 (Method Not Allowed).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
         at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
         at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
         at Remotely.Agent.Services.AgentHubConnection.Connect() in D:\a\1\s\Agent\Services\AgentHubConnection.cs:line 106

**Comment by Natan738** [comment]
@lucent-sea consegui me ajudar ?

**Comment by jakes670** [comment]
Here is a example with the headers set and Remotely not working
I am using HA Proxy in pFsense

![image](https://user-images.githubusercontent.com/31097840/216252468-074a562d-fc21-47e7-b34d-632166fcc11b.png)

Here is the logs on remotely

![image](https://user-images.githubusercontent.com/31097840/216252547-b4f6b54e-77ec-4e13-9132-bf209f4a5837.png)

**Comment by lucent-sea** [comment]
I added an option in the latest version to bypass proxy settings and force the client to use HTTPS.

![image](https://user-images.githubusercontent.com/20995508/216487494-ad7bb237-5fa9-489a-8562-9903628894ae.png)

Please keep in mind, however, that if you're needing to use this option, that means that the proxy settings are misconfigured.

Just because the `X-Forwarded-Proto` header is present does not mean ASP.NET Core will use it.  It's for security.  All proxies in the chain must be trusted, and they need to appear in correctly in `X-Forwarded-For`. 

This has nothing to do with Remotely.  This is all ASP.NET Core.  If you think you've configured it correctly and it's still not working, please open an issue in https://github.com/dotnet/aspnetcore.

**Comment by DeAlexPesh** [comment]
> I added an option in the latest version to bypass proxy settings and force the client to use HTTPS.

You're the best !!!
Now need to add the localization feature and the added custom.css

**Comment by jakes670** [comment]
Awesome Jarod, thanks for the update !
