### ISSUE TITLE
Smartscreen issues on Win10 + 11

### ISSUE THREAD

**Issue by modem7** [immense/Remotely#599]
Getting this issue on Win10 + 11. 

I understand from https://github.com/immense/Remotely/issues/551 that it'd require a certificate.

I'm just curious if Immense will be investigating.

![image](https://user-images.githubusercontent.com/4349962/219764509-bea465c2-901f-4f73-a5ca-678aacd94163.png)

Version: 2023.02.14.2047

**Comment by Scobber** [comment]
if you have your own internal PKI then you could sign the exe yourself. 
if you don't have ADCS or similar, you could self sign your own root then sign a code sign certificate against that. 
you could also exclude the installer locations, the installer exe and the install location from defender. In my environment we have defender installed with all the mitigations enabled. and we get around internally built software by signing it with a IT certificate.
in any case there are ways around it

**Comment by vitormfgoncalves** [comment]
In my case, in addition to the SmartScreen thing, it also request admin previleges.
In a restricted environment, non-admin users are unable to run the client.

**Comment by lucent-sea** [comment]
> In my case, in addition to the SmartScreen thing, it also request admin previleges. In a restricted environment, non-admin users are unable to run the client.

The quick support app is compiled with execution level set to "highestAvailable".  If the executing account is an admin, it will attempt to run elevated and do a UAC prompt.  If the account is a standard user, it will run un-elevated without prompting.

However, I don't have any new information yet about a commercial code-signing certificate.

**Comment by vitormfgoncalves** [comment]
> > In my case, in addition to the SmartScreen thing, it also request admin previleges. In a restricted environment, non-admin users are unable to run the client.
> 
> The quick support app is compiled with execution level set to "highestAvailable". If the executing account is an admin, it will attempt to run elevated and do a UAC prompt. If the account is a standard user, it will run un-elevated without prompting.
> 
> However, I don't have any new information yet about a commercial code-signing certificate.

I dont think its a code-signing problem, but can be related.
I testd in computer in a Active Directory domain, and the user was a regular user without admin previleges.
The UAC is enabled domain-wide, but I dont think its a problem in this case.

Maybe the app shouldn't probe for permissions (if I correctly understood). Maybe the user should be responsible for runing the app as admin like other apps.

**Comment by lucent-sea** [comment]
> Maybe the app shouldn't probe for permissions (if I correctly understood)

The app doesn't probe.  The manifest is read before any application code is executed.  This is a standard Win32 thing and not specific to Remotely.

More info here:  https://learn.microsoft.com/en-us/windows/win32/sbscs/application-manifests#trustinfo

**Comment by lucent-sea** [comment]
With specific attention to this part here:

![image](https://github.com/immense/Remotely/assets/20995508/b07ea6de-2c0d-453f-85fe-2328cadc2f62)

**Comment by vitormfgoncalves** [comment]
As stated in the docs, if the _requestedExecutionLevel_ is set to _highestAvailable_, the application will run at the highest permission level that it can.

The docs also state that "If the highest available permission level is higher than the level of the opening process, the system prompts for credentials."

As I understand, with this the app will always make a UAC request because, thanks to the UAC being enabled, there is a higher permission avaliable. This results in a User/Password prompt to run the app and most of the times users simply cancel and the app will not run.

In my opinion, any app shoud be run with the least permissions possible, and the users are responsible for elevation if necessary.
Going back to the docs, there is a _asInvoker_ option that will run with the same permissions as the process that started it. Maybe this should be the default _requestedExecutionLevel_.

**Comment by lucent-sea** [comment]
> Setting the level to 'highestAvailable' ensures that the application will run successfully with both users who are members of the Administrators group and those who are not. 

Here's a recording of opening it as a standard user.

https://github.com/immense/Remotely/assets/20995508/a597223b-b582-4342-aa37-15169067ba86

It was originally set to `asInvoker`.  But I received complaints from some people that they didn't want to have to go through the extra "Run as administrator" step.

I guess sometimes you just can't please everyone.

**Comment by vitormfgoncalves** [comment]
> I guess sometimes you just can't please everyone.

You are absolutely right in that.

The app could work very well in most scenarios. In mine doesn't. I Just reported my problem.
Anyone involved in this project should evaluate if this should be investigated.

I already moved on. As it is, I cant deploy it. I dont have time to chase problems.

None the less, if you see from a security standpoint, the least privilege principle should apply, and I dont think Im wrong in that.

**Comment by bitbound** [comment]
> None the less, if you see from a security standpoint, the least privilege principle should apply, and I dont think Im wrong in that.

Many Windows processes get auto-elevated without any UAC prompt when opened by a user who's in the Administrator group.  Task Manager, Device Manager, Computer Management, etc.

If Remotely were to run un-elevated for admin users, you wouldn't be able to interact with any of those windows through Remotely.  And worse, once those windows got focus, you'd lose all keyboard and mouse input completely.  You'd be stuck on that window, unable to interact with it and unable to change focus.

The current execution level is appropriate for the scenario.  If an admin is using it, it should run elevated, or it won't function properly.

**Comment by vitormfgoncalves** [comment]
> If Remotely were to run un-elevated for admin users, you wouldn't be able to interact with any of those windows through Remotely. And worse, once those windows got focus, you'd lose all keyboard and mouse input completely. You'd be stuck on that window, unable to interact with it and unable to change focus.

That is exactly how Anydesk, TeamViewer, Rustdesk and others behave when you run them without install. That's why they normally have a windows service running in the background.

> The current execution level is appropriate for the scenario. If an admin is using it, it should run elevated, or it won't function properly.

As I said, I already moved on. I'm entitled to have an opinion. Yours could be different and that's all right.

**Comment by bitbound** [comment]
> As I said, I already moved on. I'm entitled to have an opinion.

Agreed.  It's totally fine that you have your opinion on it, even if it differs from mine.

The reason I'm responding, and continue to do so now, is that others may read these comments and misconstrue that I've made design choices that adversely impact security.  I feel obligated to those potential readers to explain the considerations that went into these decisions.

To that end, I'd like to point out that TeamViewer QuickSupport does indeed perform a UAC prompt for admins, though it uses a different mechanism and uses even higher elevation.

`TeamViewerQS.exe` will run unelevated and extract the other binaries to a temp folder.   If the prompt is accepted, it will launch `TeamViewer.exe` (the UI app that shows ID/password) elevated, using your user account.  However, it will use the admin rights to elevate `tv_w32.exe` and `tv_w64.exe` even further, running under the `SYSTEM` account and having the same permission level as a Windows service.

These processes are then used to launch `TeamViewer_Desktop.exe` when the remote control session starts, also under the `SYSTEM` account.

![image](https://github.com/immense/Remotely/assets/20995508/376a6fea-dce1-4307-af61-98031d3cbcd6)


This additional elevation is required to clone the security token from the `winlogon.exe` process, which allows the app to capture and send input to UAC and Windows Logon screens.

I felt this was too intrusive and decided not to implement it this way, which is why there's an explicit "Elevate to Service" button.

**Comment by Scobber** [comment]
@vitormfgoncalves I don't see why you can't deploy it, I've deployed the vanilla version fine in this environment, using Intune

perhaps if you can't deploy it with your current strategy its time to re evaluate your system management. 

if anyone would like the deets shared for Intune deployment I'm happy to share

**Comment by Scobber** [comment]
and FWIW, signing the binaries with sign tool and a codesign cert will remove the smart screen portion of the prompts

**Comment by brl33** [comment]
Just quick ask Did u read all t&c  ur version WIN 11? .Beter ...just fire on Wireshark and chk admin filters on ur mashine ..

**Comment by vitormfgoncalves** [comment]
> @vitormfgoncalves I don't see why you can't deploy it, I've deployed the vanilla version fine in this environment, using Intune
> 
> perhaps if you can't deploy it with your current strategy its time to re evaluate your system management.
> 
> if anyone would like the deets shared for Intune deployment I'm happy to share

No cloud-dependent systems are allowed in my current environment. Everything is self hosted. So... no Intune.

> and FWIW, signing the binaries with sign tool and a codesign cert will remove the smart screen portion of the prompts

As I said before, I already moved on. I dont have time to chase problems.
