### ISSUE TITLE
Instruct client to use new server from the old server?

### ISSUE THREAD

**Issue by leifnel** [immense/Remotely#677]
In the near future, I need to install the server on a new ip and domain.

Is there a way to run a script from the server to change the configuration on the clients?

I can run it manually when the client logs in; I don't want to log into the client manually and do a change.

**Comment by bitbound** [comment]
There's an undocumented feature to do this, since I needed it once too.

Once the new server is set up and Remotely is running on it, do this on the old one.  In appsettings.json, under `ApplicationOptions`, create a property named `ServerUrl`, with the value being the URL for the new server (e.g. "https://remotely.example.com"). 

Then restart the old server.  As the clients reconnect, they should switch over to the new one.

**Comment by leifnel** [comment]
One need to get the old organization id to the new server, otherwise the client can't log in
