### ISSUE TITLE
 Text input on the remote machine

### ISSUE THREAD

**Issue by Natan738** [immense/Remotely#866]
Good afternoon,
When using version v2023.06.19.0759 I was able to insert text into a certain client program by accessing his machine using remotely, but from version v2023.07.20.1533 when connected to his machine I can no longer type in the client program. client, I believe it has to do with changes in Immense.RemoteControl or something like that that was modified in version v2023.07.20.1533.

**Comment by OliPassey** [comment]
Seeing this as well. When connecting to Win11 machines and typing a "Paste" prompt constantly pops up and stopping me from writing text.

**Comment by knumsi** [comment]
First: Aweseome project, thank you!

For me this message poped up on my 2 win11 machines as well
Version: 2024.02.23.1927
But suddenly it disappeared - no changes done...


Edit 1 day later: Showing up on the other pc. Browswer is most recent Firefox
![2024-06-26 08_21_05- Remote Control Session – Mozilla Firefox](https://github.com/immense/Remotely/assets/13940293/38f7a82c-d627-4e9b-b3b0-3ef6a0fe2b91)

Strangely it opens as well, when you click on the menubar, urlbar, etc of the browser...
![2024-06-26 08_21_05- Remote Control Session – Mozilla Firefox -1](https://github.com/immense/Remotely/assets/13940293/b02605a9-1132-4cd1-be87-021a0fe0f0ef)

**Comment by bitbound** [comment]
This is due to a recent security restriction imposed in Firefox and Safari.  This has been "fixed" in the [latest release](https://github.com/immense/Remotely/releases/tag/v2024.06.27.1520).  However, background clipboard syncing is no longer possible in Firefox/Safari, and possibly other browsers if they follow suit in the future.

Here's the relevant section from the release notes:

![image](https://github.com/immense/Remotely/assets/20995508/02fc80e3-6041-40f0-9688-dcd12735f3b7)
