### ISSUE TITLE
Latest Version - Windows install download just downloads PowerShell Script

### ISSUE THREAD

**Issue by Articical** [immense/Remotely#875]
**Describe the bug**
A clear and concise description of what the bug is. Ideally with a screenshot if applicable.

When attempting to download the background windows client via the "Downloads" page, the windows powershell script downloads and not the EXE.

**To Reproduce**

Go to "Downloads"
Select "Windows Installer (x64/x86)"
Install-Remotely.ps1 will then download

**Remotely Version**
Server (can be found on about page): 2024.02.23.1927
Agent (can be found in device card): N/A

**Expected Behavior**

Previous versions that I have used have always downloaded an EXE setup file as opposed to a powershell file.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone13]

**Additional Context**

- [x] I am running Remotely in Docker and not on my QNAP, Synology, or Internet Connected Toaster

**Comment by SoWhy** [comment]
According to https://github.com/immense/Remotely/releases/tag/v2024.02.22.1231, this is a known problem since the latest versions, see commit https://github.com/immense/Remotely/commit/07905eedaf0fb0196ebd758ce414e3b425e7edaa

**Comment by bitbound** [comment]
This was intentional.  The EXE installer will no longer be used.  It was using a legacy version of .NET (called .NET Framework with WPF).  The end goal was to make a cross-platform installer with Avalonia UI, or make the agent a self-contained EXE with CLI options to install itself, but I never got around to it.

For now, I added a copy-and-paste script for deploying the agent on a new Deploy page.  This is on the `preview` tag if you want to test it.

![image](https://github.com/immense/Remotely/assets/20995508/593d8e3e-ec67-4481-90fd-0c4a9374a178)

**Comment by blaine07** [comment]
> This was intentional. The EXE installer will no longer be used. It was using a legacy version of .NET (called .NET Framework with WPF). The end goal was to make a cross-platform installer with Avalonia UI, or make the agent a self-contained EXE with CLI options to install itself, but I never got around to it.
> 
> For now, I added a copy-and-paste script for deploying the agent on a new Deploy page. This is on the `preview` tag if you want to test it.
> 
> ![image](https://private-user-images.githubusercontent.com/20995508/336961557-593d8e3e-ec67-4481-90fd-0c4a9374a178.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDY0NDUsIm5iZiI6MTcxODEwNjE0NSwicGF0aCI6Ii8yMDk5NTUwOC8zMzY5NjE1NTctNTkzZDhlM2UtZWM2Ny00NDgxLTkwZmQtMGM0YTkzNzRhMTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDExNDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNmEyNDlhNzU5YmY4NGNkNjJkZTlkYWVmMzRlNDFjODA2NmMxNjlhZDRiYzkxNjQ3NzA1YzgzOWRmZmE0OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eVCiqNYvYi2raazEDgbYthrgU_1emT2z5gWahAvhlkk)

Unsure if unintentional of config error on my part?

Since changing to "preview" tag the PS1 wont run to install remotely on windows devices.

The fix was, on the PS1 to edit line 24 and change my Hostname to HTTP from HTTPS. :scratches head: I haven't made any other config changes other than changing to "preview" tag. 

Error I had before making this change: 6/11/2024 6:27:06 AM - Error occurred: At C:\Users\DVR\Downloads\Install-Remotely.ps1:107 char:18

Was this intentional?

**Comment by bitbound** [comment]
> Unsure if unintentional of config error on my part?

What you're describing is likely a configuration issue.  All the official docs on the issue can be found [here](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-8.0).

To try to summarize:  In order for the backend to correctly determine the host and scheme (http/https) of the original request (i.e. the URL in your browser's address bar), a few things need to happen.  First, the backend has to have the IP address of the proxy in its `KnownProxies` list.  Second, the correct forward headers need to be set in the requests proxied to the backend.  And lastly, if there are multiple proxies that traffic goes through, each of those need to be configured correctly.

 Without the above, the backend will see the scheme and/or host that the proxy uses.  The scheme seems to particularly problematic, so I added this option on the Server Config page:

![image](https://github.com/immense/Remotely/assets/20995508/409e2a30-22aa-42c2-ac62-e5134a5747ac)

Enabling this will force all the install scripts to use HTTPS, regardless of what it sees from the proxy.

**Comment by blaine07** [comment]
> > Unsure if unintentional of config error on my part?
> 
> What you're describing is likely a configuration issue. All the official docs on the issue can be found [here](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-8.0).
> 
> To try to summarize: In order for the backend to correctly determine the host and scheme (http/https) of the original request (i.e. the URL in your browser's address bar), a few things need to happen. First, the backend has to have the IP address of the proxy in its `KnownProxies` list. Second, the correct forward headers need to be set in the requests proxied to the backend. And lastly, if there are multiple proxies that traffic goes through, each of those need to be configured correctly.
> 
> Without the above, the backend will see the scheme and/or host that the proxy uses. The scheme seems to particularly problematic, so I added this option on the Server Config page:
> 
> ![image](https://private-user-images.githubusercontent.com/20995508/338667669-409e2a30-22aa-42c2-ac62-e5134a5747ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMjQwODUsIm5iZiI6MTcxODIyMzc4NSwicGF0aCI6Ii8yMDk5NTUwOC8zMzg2Njc2NjktNDA5ZTJhMzAtMjJhYS00MmMyLWFjNjItZTUxMzRhNTc0N2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDIwMjMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYThiZTE3MTc3YTU4Mzc3YmIwNWUwYTBhNTdkYzU0ZTljMDgxYzBlNThhNmUzYjE0ZGFkOTNlYzVlNjllMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jRpvZRgWCR5ieG8DK7SS5oIVjhCngE4FMmi9MXZRSV4)
> 
> Enabling this will force all the install scripts to use HTTPS, regardless of what it sees from the proxy.

Yes, so I'll be honest here - your link is way above my comprehension.

I think you're on right track though; a proxy issue. 

Currently going from Cloudflare Tunnel/Proxy>Internal Nginx Proxy Manager> Remotely.
Would it work/be better if I went Cloudflare>Remotely and removed the internal "forward" through Nginx Proxy Manager? Would be one less place to have a mis-configured proxy? Issue is coming through Cloudflare as a Proxy I have no idea how I would set "known proxy" IP since with Cloudflare it changes?

**Comment by blaine07** [comment]
![image](https://github.com/immense/Remotely/assets/63940698/85baf894-4f2c-4d8f-9c81-4aeed07e6abb)
I dunno, I am still not sure something else isn't wrong though?
