### ISSUE TITLE
change the port

### ISSUE THREAD

**Issue by kbtang88** [immense/Remotely#882]
hi there i want know how to change the port address because i have some running on 5000 like bitwarden.

**Comment by Daniel-Haurich** [comment]
Hi,
Can you tell my if you run it over docker or normaly ?
If on docker you can easily change it in the docker-compose.yml file.

Regards
Daniel

**Comment by knumsi** [comment]
Docker:
https://github.com/immense/Remotely?tab=readme-ov-file#port-configuration

**Comment by ctf830** [comment]
This issue is not related to remotely. Please google first before asking.

For every docker compose file, you can change the port u desire and map it to the docker by changing the ports on the left side. eg:

    ports:
      - "5001:5000"

![image](https://github.com/user-attachments/assets/0b4b6781-54b3-4ab7-990a-81ffc64dea0b)

**Comment by bitbound** [comment]
Thanks, @ctf830 .

I updated the readme and the comments in compose.  Hopefully that eliminates any confusion.
