### ISSUE TITLE
can't connect if i rename the exe

### ISSUE THREAD

**Issue by Giuseppe-TD** [immense/Remotely#905]
why if i rename the exe (portable) i can't connect to the server?
the portable versione ask me to add the server address when open it

**Comment by bitbound** [comment]
Please see release notes.

**Comment by bitbound** [comment]
Expanding on this (was busy the other day).

When you run the Docker container, you get the same image as everyone else.  The Remotely_Desktop.exe app is contained in the image, so it's also the same as everyone else's.

How can the app know what your server URL is so it can connect to it?  By default, there's no way for it to know.

It can't be hard-coded in the EXE unless you modify the source code and compile your own version.  So we need to generate something dynamically at the moment it's downloaded, since the URL of the incoming request will be your server's specific URL.

Previously, I was injecting binary-encoded data into the file stream itself as it's being downloaded.  However, this breaks the digital signature.  So even if I were to use a trusted commercial code-signing certificate to avoid SmartScreen warnings, this process would have broken it.

So instead, it's now embedding the server URL into the file name.  This leaves the digital signature intact.
